deployment:
    tasks:
        - export DEPLOYPATH=~/app.thomas-claireau.fr/fcc/caesars-cipher
        - /bin/cp -R * $DEPLOYPATH
        - /bin/cp -R .htaccess $DEPLOYPATH
        - $DEPLOYPATH/build.sh 2>&1
